all: xballoon                                                                                                                                                                                                
balloon: xballoon.c
	gcc xballoon.c -o xballoon
clean:
	rm xballoon
